import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ParticleBackground from "./components/ParticleBackground";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Sahil Sharma",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/HERO.png",
        sizes: "32x32",
        type: "image/png",
      },
      {
        url: "/HERO.png",
        sizes: "16x16",
        type: "image/png",
      },
      {
        url: "/HERO.png",
        sizes: "192x192",
        type: "image/png",
      },
      {
        url: "/HERO.png",
        sizes: "512x512",
        type: "image/png",
      },
    ],
    shortcut: "/HERO.png",
    apple: [
      {
        url: "/HERO.png",
        sizes: "180x180",
        type: "image/png",
      },
    ],
    other: [
      {
        rel: "apple-touch-icon-precomposed",
        url: "/HERO.png",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
      >
        <ParticleBackground />
        <div className="relative" style={{ zIndex: 1 }}>
          {children}
        </div>
      </body>
    </html>
  );
}
